<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\$(Configuration)\Mods\mod</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VINTAGE_STORY)/VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VSSurvivalMod">
      <HintPath>$(VINTAGE_STORY)/Mods/VSSurvivalMod.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VSEssentials">
      <HintPath>$(VINTAGE_STORY)/Mods/VSEssentials.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VSCreativeMod">
      <HintPath>$(VINTAGE_STORY)/Mods/VSCreativeMod.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(VINTAGE_STORY)/Lib/Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="protobuf-net">
      <HintPath>$(VINTAGE_STORY)/Lib/protobuf-net.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="assets\**">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="assets\woodstain\blocktypes\wood\woodtyped\stainedfence-free.json" />
    <None Remove="assets\woodstain\blocktypes\wood\woodtyped\stainedfence-snow.json" />
    <None Remove="assets\woodstain\blocktypes\wood\woodtyped\stainedfencegate.json" />
    <None Remove="assets\woodstain\blocktypes\wood\woodtyped\stainedlog-debarked.json" />
    <None Remove="assets\woodstain\patches\compat\wildcrafttree\stainedfence-free.json" />
    <None Remove="assets\woodstain\patches\compat\wildcrafttree\stainedfence-snow.json" />
    <None Remove="assets\woodstain\patches\compat\wildcrafttree\stainedfencegate.json" />
    <None Remove="assets\woodstain\patches\compat\wildcrafttree\stainedlog-debarked.json" />
    <None Remove="assets\woodstain\sounds\block\door.ogg" />
    <None Remove="assets\woodstain\sounds\block\hewnfancegate.ogg" />
    <Content Include="modinfo.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
